### ISSUE TITLE
lights switch not working in Hass addon

### ISSUE THREAD

**Issue by Modderhut** [timmo001/home-panel#1014]
# Description
when controlling for example a hue light; status icon, color temperature and brightness work as expected but I'm unable to turn the light on or off when clicking the light bulb icon. Another user posed the same issue on addon-home-panel git page.

## How to reproduce the issue (if applicable)
this is using the hass.io addon, create new card with any light entity.

**Comment by czadikem** [comment]
I am having the same isssue

**Comment by seeq5** [comment]
i am having the same issue. It appears to read from home assistant fine but cannot respond back in some instances. Hue lights will feedback brightness and colour but will not switch on and off. Other switches do not respond either.

**Comment by KoenHaemels** [comment]
I'm also having the same issue, please fix this!

**Comment by timmo001** [comment]
Yep, this seems to have started happening for my addon too

**Comment by KoenHaemels** [comment]
@timmo001 do you update your docker image also?

https://hub.docker.com/r/timmo001/home-panel

**Comment by timmo001** [comment]
> @timmo001 do you update your docker image also?
> 
> https://hub.docker.com/r/timmo001/home-panel

Releasing to docker hub now, addon follows
