### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by sagilo** [timmo001/home-panel#109]
# Description
I'm using Docker Compose to setup home-panel.
Home assistant configured **on the same system** (running on Ubuntu 16.04 but not via docker)

## How to reproduce the issue
I've typed both API and HA url's (tried several options), I keep getting errors when I click log-in

On logs:
```
home-panel-api_1  | Error: EISDIR: illegal operation on a directory, read
home-panel-api_1  |     at Object.fs.readSync (fs.js:690:18)
home-panel-api_1  |     at tryReadSync (fs.js:554:20)
home-panel-api_1  |     at Object.fs.readFileSync (fs.js:597:19)
home-panel-api_1  |     at getConfig (/usr/src/app/app/routes/login.js:23:30)
home-panel-api_1  |     at app.post (/usr/src/app/app/routes/login.js:55:32)
home-panel-api_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
home-panel-api_1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
home-panel-api_1  |     at /usr/src/app/node_modules/body-parser/lib/read.js:130:5
home-panel-api_1  |     at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)
home-panel-api_1  |     at done (/usr/src/app/node_modules/raw-body/index.js:213:7)
``` 

## Screenshots 
https://image.ibb.co/b5KAPp/Screenshot_2018_09_14_17_27_03.png

Thank you

**Comment by timmo001** [comment]
Check your `config.json` is valid with a tool like this:

https://jsonformatter.curiousconcept.com/

**Comment by sagilo** [comment]
I've tested the json, it's valid.
I've also stripped out almost all items and now it looks like that :
```
{
  "theme": {
    "custom": [
      {
        "name": "Midnight",
        "base": "dark",
        "overrides": {
          "backgrounds": {
            "main": "#383c45",
            "default": "#383c45",
            "card": {
              "on": "pink[600]",
              "off": "#434954",
              "disabled": "#7f848e"
            }
          },
          "text": {
            "light": "grey[50]",
            "main": "grey[100]"
          }
        }
      }
    ]
  },
  "header": {
  },
  "items": [
  ]
}
```

But it didn't work with real items as well.

**Comment by timmo001** [comment]
Can you post your docker-compose file?

Are you sure your `config.json` is accessible?

**Comment by sagilo** [comment]
OK. I've moved all the data from `/home/docker/home-panel/` to `/home/user/docker/home-panel/` and now it works.
It does a bit weird since the docker runs as root but I guess it still couldn't access these files.
Thank you very much for your assistance and for this great app!

**Comment by timmo001** [comment]
No problem :+1:
