### ISSUE TITLE
Slowdowns over time

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#117]
# Description

The application is slowing down over time on some lower powered devices. This is causing buttons and scrolling to become unresponsive

## How to reproduce the issue (if applicable)

Leave the app running for an extended period of time in the foreground.

**Comment by timmo001** [comment]
I originally thought this was something to do with the WebSocket, but found that the theme was being set on every update of entities which was causing the JSS to update and the application to redraw on every update.

I have moved the method call to a lower component so it is called once. This seems to have sped the application up exponentially. This was done in this PR: 

#111 

This was likely the cause of slowdowns over time as well as what was causing lag with scrolling or any other interaction in the app :tada:

**Comment by aptonline** [comment]
I am also seeing this issue over time.
