### ISSUE TITLE
Unable to change any attributes under theme header

### ISSUE THREAD

**Issue by XeSSiV** [timmo001/home-panel#1183]
# Description
Not able to modify any attributes under the Theme header.
Changes are shown, but then revert to previous when you leave and return to the window.
Changing Primary and secondary colours worked initially but then stopped working. Inspecting when changes are made, I get these below. The Primary and Secondary colours were not set to lime at the time of the changes. I also am unable to change any other attributes under the Theme section. They give me the same errors as below.
Main.tsx:119 Uncaught TypeError: Cannot create property 'background_default' on string 'lime'
at Object.B [as handleUpdateConfig] (Main.tsx:119)
at Item.tsx:109
Main.tsx:119 Uncaught TypeError: Cannot create property 'background_paper' on string 'lime'
at Object.B [as handleUpdateConfig] (Main.tsx:119)
at Item.tsx:109

## How to reproduce the issue (if applicable)
- Install Home Panel Addon v1.7.3 on to a supervised Home Assistant installation (specific information for my setup in Additional Information section)
- Create a Home Panel user and login
- Try to edit the Theme section - if it does work, then leave the window and go back into it
- Changes should not take effect, and inspecting the code gives errors like the above

## Additional information
Home Assistant Supervised on a RPi 3b+
HA Core v110.6
Supervisor v227
HassOS v4.10

**Comment by timmo001** [comment]
I'm unable to replicate this issue, at least in the latest code.

I'll release an update to the app and see if this is the case

**Comment by timmo001** [comment]
Won't be updating today at least. CI and edge image are currently not working

**Comment by timmo001** [comment]
I've released a new version. Please reopen if you are still facing these issues after updating. Thanks

**Comment by kingtao1024** [comment]
I have met the same problem, I can't modify the color

**Comment by Th30wl** [comment]
Same happens to me. This started happening after I tried to set image url for the background.
Version information:
` Add-on version: 1.8.3`
` System: Ubuntu 20.04.1 LTS  (amd64 / qemux86-64)`
` Home Assistant Core: 0.116.4`
` Home Assistant Supervisor: 249`

You can see the following error in console:
`Uncaught TypeError: Cannot create property 'primary' on string 'purple'
    at Object.z [as handleUpdateConfig] (Main.tsx:121)
    at Item.tsx:113`

**Comment by Th30wl** [comment]
It seems that there is an issue with saving the config file. I have created a backup and the "theme" node seems wrong:
```
{
   "general":{
      "autohide_toolbar":true,
      "dense_toolbar":true
   },
   "theme":"purple",
   "header":{
      "time_show":true,
      "time_military":true,
      "time_location":2,
      "date_show":true,
      "date_format":"dddd, MMMM Do YYYY",
      "date_location":0,
      "date_font_size":"18",
      "time_font_size":"18"
   },
   "pages":[
      {
         "key":"abcdefghijklmnop",
         "name":"",
         "icon":"home"
      }
   ],
   "groups":[
      {
         "key":"abcd1234efgh4567",
         "page":"abcdefghijklmnop",
         "name":"",
         "width":"4"
      },
      {
         "key":"sECv8T6W6VIxmyOk",
         "name":"",
         "page":"abcdefghijklmnop",
         "width":"2",
         "cards":[
            
         ]
      },
      {
         "key":"deiP7BHROrzZIDxG",
         "name":"",
         "page":"abcdefghijklmnop",
         "width":2,
         "cards":[
            
         ]
      }
   ],
   "cards":[
   ],
   "news":{
      
   }
}
```

**Comment by Th30wl** [comment]
@timmo001 I think I have found the source of this bug, config file is not being saved properly. I have exported the settings and noticed that the "theme" node is wrong. This also explains  the error message seen in console.

```
{
   "general":{
      "autohide_toolbar":true,
      "dense_toolbar":true
   },
   "theme":"purple",
   "header":{
      "time_show":true,
      "time_military":true,
      "time_location":2,
      "date_show":true,
      "date_format":"dddd, MMMM Do YYYY",
      "date_location":0,
      "date_font_size":"18",
      "time_font_size":"18"
   },
   "pages":[
      {
         "key":"abcdefghijklmnop",
         "name":"",
         "icon":"home"
      }
   ],
   "groups":[
      {
         "key":"abcd1234efgh4567",
         "page":"abcdefghijklmnop",
         "name":"",
         "width":"4"
      },
      {
         "key":"sECv8T6W6VIxmyOk",
         "name":"",
         "page":"abcdefghijklmnop",
         "width":"2",
         "cards":[
            
         ]
      },
      {
         "key":"deiP7BHROrzZIDxG",
         "name":"",
         "page":"abcdefghijklmnop",
         "width":2,
         "cards":[
            
         ]
      }
   ],
   "cards":[
   ],
   "news":{
      
   }
}
```

**Comment by Th30wl** [comment]
@XeSSiV , @kingtao1024 here is the workaround I use:

1. in the configuration page create a backup of your current config
1.a I recommend formatting it using (any) json formatter tool so that  you can see the structure better
2. You will find the "theme" node looking something like: `"theme":"purple",`
3. Replace it with the manually modified settings, eg:
```
"theme":{
      "type":"dark",
      "primary":"orange",
      "secondary":"teal",
      "background_default":"#303030",
      "background_paper":"#383c45",
      "link_color":"#00ccff"
   },
```
5. Save file and restore it to Home Panel configuration
