### ISSUE TITLE
autohide_navigation feature

### ISSUE THREAD

**Issue by RaveGun** [timmo001/home-panel#1261]
# Description
The auto hide Navigation feature is no longer working.
Is this intended or by mistake?
I also did not found any reference to the configuration item in the code.

## How to reproduce the issue (if applicable)
I am running the latest version of the add-on in Home Assistant and the auto-hide is just not working.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/4079754/89394977-06643a80-d70d-11ea-8eb8-f7ff625edef3.png)
![image](https://user-images.githubusercontent.com/4079754/89395027-14b25680-d70d-11ea-8971-bfd91163076e.png)

## Additional information
I hope you are well and safe.

**Comment by timmo001** [comment]
From your screenshot, I see you have auto hide toolbar turned off...?

**Comment by RaveGun** [comment]
Hi,

Yes it is off, but just to clarify:
- on top is the toolbar?
- on the bottom is the navigation bar?
The comments for the Nav- and Tool- bars are also the same and it is confusing 😄 

Because I do not want to have the tiles shift down when I touch a switch, I went with the autohide_toolbar = false.

The screen shots were from my computer on the 7" RPi display the nav bar covers the bottom row of tiles.
It seems that the navigation bar is also taller than it looks.
Something like this:
![image](https://user-images.githubusercontent.com/4079754/89407262-c1490400-d71e-11ea-944e-b15b9d1416bf.png)
