### ISSUE TITLE
Web Ui config error 500 /config/set

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#130]
prefer to use JSON you still can, from the api like usual. (be sure to report any bugs you find to the issue tracker)

I have tweaked the UI, adding animations, fixing margins, position issues etc.
You can also disable time and date to reduce the size of the header further.

https://git.timmo.xyz/home-panel/configuration/#time 15

Breaking change
There is one change to the config, which moves date format to the date object. See: https://git.timmo.xyz/home-panel/configuration/#date 6

18 DAYS LATER

thundergreen
1 
1d
Maybe I’m too stupid but I cannot save pages items etc …logs show

Creating user…
POST /login/setup 200 5.164 ms - 838
OPTIONS /config/set 204 0.212 ms - 0
POST /config/set 500 1000.075 ms - 1073
POST /config/set 500 28.711 ms - 1073
POST /config/set 500 32.613 ms - 1073
OPTIONS /config/set 204 0.419 ms - 0
POST /config/set 500 23.488 ms - 1073
POST /config/set 500 32.414 ms - 1073
POST /config/set 500 35.628 ms - 1073
OPTIONS /config/set 204 0.541 ms - 0
POST /config/set 500 41.923 ms - 1073
POST /config/set 500 26.841 ms - 1073
POST /config/set 500 29.482 ms - 1073
POST /config/set 500 40.364 ms - 1073
POST /config/set 500 36.405 ms - 1073
POST /config/set 500 31.310 ms - 1073
OPTIONS /login 204 0.333 ms - 0
User found.
POST /login 200 1.893 ms - 838
OPTIONS /config/set 204 0.313 ms - 0
POST /config/set 500 36.832 ms - 1073
POST /config/set 500 21.352 ms - 1073
POST /config/set 500 26.318 ms - 1073
OPTIONS /config/set 204 0.225 ms - 0
POST /config/set 500 16.075 ms - 1073
POST /config/set 500 44.816 ms - 1073
POST /config/set 500 23.612 ms - 1073

I try to modify the dashboard via Webinterface

Any help ?

Edit: I’m accessing via VPN…will try again locally and revert

thundergreen
1d
Just tried at home…still same issue

  Reply
You will see a count of new replies because you posted a reply to this topic.

Suggested Topics
[Monitor] Reliable, Multi-User, Distributed BT Occupancy/Presence Detection  49 232
mqtt
automation
8m
Share your Projects!
Zigbee2mqtt: getting rid of your proprietary Zigbee bridges (Xiaomi, Hue, TRADFRI)  276 189
13m
Share your Projects!
[ALPHA testing] HA Client - native Android client for Home Assistant  12
14m
Share your Projects!
Using a Vera Edge as a network-attached zwave device (skipping the vera software)  1
3h
Share your Projects!
Howto create battery alert without creating a template for every device  14 6
5h
Share your Projects!
There are 282 unread and 162 new topics remaining, or browse other topics in 
Share your Projects!
History
         Edit Post
   thundergreen 1 day
Maybe I’m too stupid but I cannot save pages items etc …logs show

Creating user…
POST /login/setup 200 5.164 ms - 838
OPTIONS /config/set 204 0.212 ms - 0
POST /config/set 500 1000.075 ms - 1073
POST /config/set 500 28.711 ms - 1073
POST /config/set 500 32.613 ms - 1073
OPTIONS /config/set 204 0.419 ms - 0
POST /config/set 500 23.488 ms - 1073
POST /config/set 500 32.414 ms - 1073
POST /config/set 500 35.628 ms - 1073
OPTIONS /config/set 204 0.541 ms - 0
POST /config/set 500 41.923 ms - 1073
POST /config/set 500 26.841 ms - 1073
POST /config/set 500 29.482 ms - 1073
POST /config/set 500 40.364 ms - 1073
POST /config/set 500 36.405 ms - 1073
POST /config/set 500 31.310 ms - 1073
OPTIONS /login 204 0.333 ms - 0
User found.
POST /login 200 1.893 ms - 838
OPTIONS /config/set 204 0.313 ms - 0
POST /config/set 500 36.832 ms - 1073
POST /config/set 500 21.352 ms - 1073
POST /config/set 500 26.318 ms - 1073
OPTIONS /config/set 204 0.225 ms - 0
POST /config/set 500 16.075 ms - 1073
POST /config/set 500 44.816 ms - 1073
POST /config/set 500 23.612 ms - 1073

Each time I try to make a change via Webinterface it throws those error in api logs :/

<blockquote><img src="../favicon.ico" width="48" align="right"><div><strong><a href="https://git.timmo.xyz/home-panel/configuration/#time">Configuration - Home Panel Docs</a></strong></div><div>A touch-compatible web-app for controlling the home</div></blockquote>
<blockquote><img src="../favicon.ico" width="48" align="right"><div><strong><a href="https://git.timmo.xyz/home-panel/configuration/#date">Configuration - Home Panel Docs</a></strong></div><div>A touch-compatible web-app for controlling the home</div></blockquote>

**Comment by timmo001** [comment]
There are no errors in those logs, however I have noticed the configuration not updating in the Hass.io addon. Is this what you are using in your instance of Home Panel?

**Comment by thundergreen** [comment]
I'm using docker container so much the same yeah . I'd love getting this running as this is absolutely awesome  is there anything I can do to debug? I run the latest API docker image as well .seems some write issues  I guess

**Comment by timmo001** [comment]
I have just released a new version of the API. Please update your image and see if the issue has been fixed. More info on the issue here:

https://community.home-assistant.io/t/home-panel-a-touch-compatible-webapp-for-controlling-the-home/62597/157?u=timmo001

If your issue is still not resolved, feel free to reopen this issue and share any logs as per:

https://git.timmo.xyz/home-panel/troubleshooting/
