### ISSUE TITLE
confi page

### ISSUE THREAD

**Issue by addboy58** [timmo001/home-panel#1305]
# Description
Can not save to API or background filed.

**Comment by timmo001** [comment]
More detail required.

https://home-panel-docs.timmo.dev/troubleshooting/

**Comment by addboy58** [comment]
When trying to past in "News API" in the config panel under the news API book, the link is not activated or saved. I do not see a save button or anyway to save charges in any of the config fields.
Thx
Dave

**Comment by timmo001** [comment]
An API key is required to get news feeds which can be set under the configuration page/section of the app. Once you have set that, you can add a card with the type news
