### ISSUE TITLE
Disable pages bar when there is only 1 page

### ISSUE THREAD

**Issue by sagilo** [timmo001/home-panel#135]
# Description
The page bar appears even if there is only 1 page (default)
The bar reduced the page height and creates unnecessary scrolling 

## How to reproduce the issue (if applicable)
Use only 1 page

## Screenshots (if applicable)
![img](https://i.imgur.com/V4VWstT.png)

**Comment by timmo001** [comment]
Funny thing is, I explicitly add the home tab if there is none. 

I guess on smaller screens this can get in the way if you only have one page

**Comment by sagilo** [comment]
haha.. but actually, I went to the pages section and created a page, then I deleted it, and now I have an empty bar.
Anyway IMHO a bar which serves no purpose shouldn't be taking any screen space :)

**Comment by timmo001** [comment]
Change made. Will be in next release
