### ISSUE TITLE
Saving bg color fails

### ISSUE THREAD

**Issue by ylima-sa** [timmo001/home-panel#1370]
I just installed home panel and I tried to change background color, but for some reason I got an error:

```
Uncaught TypeError: Cannot create property 'background_default' on string 'indigo'
    at Object.z [as handleUpdateConfig] (Main.tsx:121)
    at Item.tsx:113

```
I am using Chrome on Windows.

Updating toggles, like "Dense Toolbar" works fine.

Very nice project 👍

**Comment by lmbss** [comment]
i have some problem including the toggles configuration. in chorme, brave and firefox on ubuntu

**Comment by michaeldavie** [comment]
I'm having this problem as well. I've tried using a private browser, reverting to earlier versions, and I'm still unable to change the colours from pink.

**Comment by ganastor** [comment]
I am having the same issue as well. I was tempted to go and change it in the container itself, but decided not to after finding this issue.
