### ISSUE TITLE
Changing Configuration settings don't apply or change.

### ISSUE THREAD

**Issue by dacool** [timmo001/home-panel#1391]
# Description

Changing Configuration settings don't apply or change.

When changing configuration settings, it's seems that it appends data to the file in
/usr/share/hassio/addons/data/a0d7b954_home-panel/config.db

And makes json file malfunction.

Running config.db file in jsonlint.com says:

Error: Parse error on line 48:
...t": 1609089488113} { "config": { "ge
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

## How to reproduce the issue (if applicable)

Install home-panel hassio addon and change configuration settings

## Additional information
Using Chrome Versio 87.0.4280.88 

Add-on version: 1.8.3
You are running the latest version of this add-on.
System: Ubuntu 20.04.1 LTS (amd64 / qemux86-64)
Home Assistant Core: 2020.12.1
Home Assistant Supervisor: 2020.12.7

**Comment by NVader2000** [comment]
Had this same issue. But now I am getting 'homeassistant.local’s server IP address could not be found.' Never hear bavk from Dev on this issue so I cannot further trouble shoot
