### ISSUE TITLE
I am unable to make any changes in the settings

### ISSUE THREAD

**Issue by cperryoh** [timmo001/home-panel#1420]
# Description
When I got to the settings and set them as I want and close and re open the window. The changes I made do not stick.

## Screenshots (if applicable)
After changing my settings
![image](https://user-images.githubusercontent.com/46071730/106326062-dde77400-6249-11eb-8f80-84a59a6dd019.png)

After reloading the config page
![image](https://user-images.githubusercontent.com/46071730/106326111-f22b7100-6249-11eb-96ce-54ca95b7e092.png)

**Comment by pluut** [comment]
Having the same issue (ovi and pi image) 
cannot save changes.

**Comment by f-sim** [comment]
I have this issue, too.

**Comment by AadKikkert** [comment]
I have the same issue too, 
Using 

Versie | core-2021.2.3
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Virtuele omgeving | false
Python versie | 3.8.7
Operating System Family | Linux
Versie van het besturingssysteem | 5.4.83-v8
CPU Architecture | aarch64
Tijdzone | Europe/Amsterdam

**Comment by danielandastro** [comment]
Same issue, on HASS running on an exclusive Debian proxmox VM

**Comment by ifol** [comment]
Same here, interesting that it worked right after installing the addon and then simply stopped as I was configuring it. Not sure what could have caused it, I restarted, updated to 2.1.1 and so on, can't pinpoint the exact moment it started doing this. Also maybe worth pointing out that when I "BACKUP" the configuration, there is only "general" settings in the produced json. I was thinking I could edit that file and restore but that doesn't seem to work either (If someone could provide a complete json I could try that, I was unable to find any online). I've tried to uninstall and install the addon again, no luck.

Please advise how to debug this issue further, I'm out of ideas that I could try.

Version | core-2021.3.4
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.10.21-sunxi64
CPU Architecture | aarch64


Host Operating System | Armbian 21.02.3 Focal
Update Channel | stable
Supervisor Version | supervisor-2021.03.6
Docker Version | 20.10.5

**Comment by frankietest6** [comment]
I'm having the exact same issue with a fresh install

# Core
Version
core-2021.3.4

# Supervisor
Version
supervisor-2021.03.6

**Comment by TuneFish41** [comment]
Same here.

The configuration in config.db is only appended on change and not overwritten.

Example:

`{"config":{"general":{"autohide_toolbar":false,"dense_toolbar":false},"theme":{"type":"dark","primary":"green","secondary":"green","background_default":"#303030","background_paper":"#383c45","link_color":"#00ccff"},"header":{"time_show":true,"time_military":false,"time_location":0,"date_show":true,"date_format":"Do MMMM YYYY","date_location":1},"pages":[{"key":"abcdefghijklmnop","name":"Home","icon":"home"}],"groups":[{"key":"abcd1234efgh4567","page":"abcdefghijklmnop","name":"Welcome Group","width":3}],"cards":[{"key":"1234abcd5678efgh","group":"abcd1234efgh4567","type":"markdown","width":3,"title":"Welcome!","content":"Hi there! Thanks for using Home Panel.\n\nMake sure to read the [docs](https://home-panel-docs.timmo.dev) to get the most out of the app."}]},"userId":"24nAcL4c061ZbnsD","createdAt":1617408813085,"_id":"gbyaD1daME1cJ7ce"}
{"config":{"general":{"autohide_toolbar":false,"dense_toolbar":false},"theme":{"type":"dark","primary":"green","secondary":"green","background_default":"#303030","background_paper":"#383c45","link_color":"#00ccff"},"header":{"time_show":true,"time_military":false,"time_location":0,"date_show":true,"date_format":"Do MMMM YYYY","date_location":1},"pages":[{"key":"abcdefghijklmnop","name":"Home","icon":"home"},{"key":"N9WQzz2MZgl392ra","name":"Page","icon":"file"}],"groups":[{"key":"abcd1234efgh4567","page":"abcdefghijklmnop","name":"Welcome Group","width":3}],"cards":[{"key":"1234abcd5678efgh","group":"abcd1234efgh4567","type":"markdown","width":3,"title":"Welcome!","content":"Hi there! Thanks for using Home Panel.\n\nMake sure to read the [docs](https://home-panel-docs.timmo.dev) to get the most out of the app."}]},"userId":"24nAcL4c061ZbnsD","_id":"gbyaD1daME1cJ7ce","updatedAt":1617409676412}
{"config":{"general":{"autohide_toolbar":false,"dense_toolbar":false},"theme":{"type":"dark","primary":"green","secondary":"green","background_default":"#303030","background_paper":"#383c45","link_color":"#00ccff"},"header":{"time_show":true,"time_military":false,"time_location":0,"date_show":true,"date_format":"Do MMMM YYYY","date_location":1},"pages":[{"key":"abcdefghijklmnop","name":"Home","icon":"home"},{"key":"N9WQzz2MZgl392ra","name":"Page","icon":"file"}],"groups":[{"key":"abcd1234efgh4567","page":"abcdefghijklmnop","name":"Welcome Group","width":3},{"key":"GSN1ccElsgnkSNdt","name":"Group","page":"N9WQzz2MZgl392ra","width":2,"cards":[]}],"cards":[{"key":"1234abcd5678efgh","group":"abcd1234efgh4567","type":"markdown","width":3,"title":"Welcome!","content":"Hi there! Thanks for using Home Panel.\n\nMake sure to read the [docs](https://home-panel-docs.timmo.dev) to get the most out of the app."}]},"userId":"24nAcL4c061ZbnsD","_id":"gbyaD1daME1cJ7ce","updatedAt":1617409681318}
{"config":{"general":{"autohide_toolbar":false,"dense_toolbar":false},"theme":{"type":"dark","primary":"green","secondary":"green","background_default":"#303030","background_paper":"#383c45","link_color":"#00ccff"},"header":{"time_show":true,"time_military":false,"time_location":0,"date_show":true,"date_format":"Do MMMM YYYY","date_location":1},"pages":[{"key":"abcdefghijklmnop","name":"Home","icon":"home"},{"key":"N9WQzz2MZgl392ra","name":"Page","icon":"file"}],"groups":[{"key":"abcd1234efgh4567","page":"abcdefghijklmnop","name":"Welcome Group","width":3},{"key":"GSN1ccElsgnkSNdt","name":"Page","page":"N9WQzz2MZgl392ra","width":2,"cards":[]}],"cards":[{"key":"1234abcd5678efgh","group":"abcd1234efgh4567","type":"markdown","width":3,"title":"Welcome!","content":"Hi there! Thanks for using Home Panel.\n\nMake sure to read the [docs](https://home-panel-docs.timmo.dev) to get the most out of the app."}]},"userId":"24nAcL4c061ZbnsD","_id":"gbyaD1daME1cJ7ce","updatedAt":1617409692728}
{"config":{"general":{"autohide_toolbar":false,"dense_toolbar":false},"theme":{"type":"dark","primary":"green","secondary":"green","background_default":"#303030","background_paper":"#383c45","link_color":"#00ccff"},"header":{"time_show":true,"time_military":false,"time_location":0,"date_show":true,"date_format":"Do MMMM YYYY","date_location":1},"pages":[{"key":"abcdefghijklmnop","name":"Home","icon":"home"},{"key":"N9WQzz2MZgl392ra","name":"Page","icon":"file"},{"key":"R7KGNLunbOft6aMQ","name":"Page","icon":"file"}],"groups":[{"key":"abcd1234efgh4567","page":"abcdefghijklmnop","name":"Welcome Group","width":3},{"key":"GSN1ccElsgnkSNdt","name":"Page","page":"N9WQzz2MZgl392ra","width":2,"cards":[]}],"cards":[{"key":"1234abcd5678efgh","group":"abcd1234efgh4567","type":"markdown","width":3,"title":"Welcome!","content":"Hi there! Thanks for using Home Panel.\n\nMake sure to read the [docs](https://home-panel-docs.timmo.dev) to get the most out of the app."}]},"userId":"24nAcL4c061ZbnsD","_id":"gbyaD1daME1cJ7ce","updatedAt":1617409694781}
root@tars:/var/lib/docker/volumes/home_panel_data/_data#
`

**Comment by connoleg** [comment]
I have this same issue. Also when changing card parameters the values stick and cannot be edited ie chart range starts with 3  and cant be overwritten, backspace over it changes to 6

**Comment by danielandastro** [comment]
Still not fixed (2.2.0 on HASS supervised) (through addon store)
