### ISSUE TITLE
how to save configuration?

### ISSUE THREAD

**Issue by JoshandNancy** [timmo001/home-panel#1637]
# Description

Hello

I've installed Home Panel via Supervisor. It works great!

But, I cannnot find how to save configuration in Home Panel. 

## How to reproduce the issue (if applicable)

If I change Theme color, it changed for a few times, though, any other options are not changed at all. If I switch to other menu (overview) and go back to configuration, all the changes in configuration are lost.

And I tried to find any save button in configuration menu, and I couldn't find any.

Am I missing something here?

I use raspberry pi 4B and installed HA with supervised version.

Anyway, thank you for your great work!

Bests,

**Comment by timmo001** [comment]
It autosaves after making a change
