### ISSUE TITLE
Cannot save config

### ISSUE THREAD

**Issue by BigWebstas** [timmo001/home-panel#1774]
# Description
Cannot save config changes.

Attempting to change the theme color
```
Main.tsx:121 Uncaught TypeError: Cannot create property 'secondary' on string 'blueGrey'
    at Object.z [as handleUpdateConfig] (Main.tsx:121:31)
    at Item.tsx:112:15
```

## How to reproduce the issue (if applicable)

1. Click on hamburger menu
2. Click on configuration
3. Attempt to change the theme color, or any setting

## Additional information
Seems to be the same issue as in these bugs 
https://github.com/timmo001/home-panel/issues/1370
https://github.com/timmo001/home-panel/issues/1715
https://github.com/timmo001/home-panel/issues/1420
https://github.com/timmo001/home-panel/issues/1391

**Comment by Shanksg** [comment]
> # Description
> Cannot save config changes.
> 
> Attempting to change the theme color
> 
> ```
> Main.tsx:121 Uncaught TypeError: Cannot create property 'secondary' on string 'blueGrey'
>     at Object.z [as handleUpdateConfig] (Main.tsx:121:31)
>     at Item.tsx:112:15
> ```
> 
> ## How to reproduce the issue (if applicable)
> 1. Click on hamburger menu
> 2. Click on configuration
> 3. Attempt to change the theme color, or any setting
> 
> ## Screenshots (if applicable)
> ## Additional information
> Seems to be the same issue as in these bugs #1370 #1715 #1420 #1391

having the same problem
