### ISSUE TITLE
"Log in to Home Assistant" via Proxy not working.

### ISSUE THREAD

**Issue by wolfswolke** [timmo001/home-panel#1916]
# Description
When i access my Home Assistant via my Website and click the "Log in to Home Assistant Buton" the Login shows up for a split second and the the Page refreshes itself.

## How to reproduce the issue (if applicable)
Put the HO with the Addon behind a NGINX Reverse Proxy (Add proxy host in HO config and enable webhook support) and log into HomePanel.

## Screenshots (if applicable)
![grafik](https://user-images.githubusercontent.com/34097612/180393526-6b993e6a-c6c9-420e-a1ac-e56f7c275ae3.png)
![grafik](https://user-images.githubusercontent.com/34097612/180393966-4dba182f-3840-4d7f-a6b4-7a82ff8363fe.png)

## Additional information
Home Panel Version: 2.5.0 (Installed from HO Add-ons)
Home Assistant 22.7.6 (Supervisor 22.07.0)

**Comment by cestnickell** [comment]
Same problem for me. Did you find a workaround?

**Comment by wolfswolke** [comment]
No i did not and i dont know how to reopen this.
