### ISSUE TITLE
Not Working on Android 6 with WallPanel apk

### ISSUE THREAD

**Issue by voodoobg** [timmo001/home-panel#210]
# Description
Home Panel not loading on Android 6 Tablet with WallPanel apk.

## How to reproduce the issue (if applicable)
Using WallPanel apk to access webpages (working OK with HADashboard). When I load the Home Panel page it displays blank screen so nothing is working.

## Screenshots (if applicable)
Its just blank screen

## Additional information
Maybe it's related with Android WebView component.

**Comment by timmo001** [comment]
Does this work in chrome? I just installed the app on my phone and it loaded fine

**Comment by voodoobg** [comment]
Yep it works on my phone also, but not on the tablet... It works everywhere else. As I said, probably its because the older version of WebView, i should check if I can update it.

**Comment by timmo001** [comment]
I will close this since it is too edge case and I cannot reproduce it. If this occurs on just the one device, I can only put it down to an outdated or unsupported browser.

Thanks
