### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mbrownnycnyc** [timmo001/home-panel#214]
# Description
![image](https://raw.githubusercontent.com/timmo001/home-panel/master/docs/resources/midnight-theme.png)

There are two panels shown on the main github page that I can not discover how to create.  One is the Weather panel, and the other is Central Heating.  I assume these simply can't be of hass type with dynamic interaction (like a light), as I just added my thermostat without luck.

## Suggested Actions
Please produce or post more example configurations of the most dynamic items, such as those described above.

I was working on dashboards with MQTTdash on my Wink Relays, but home panel would be a great and easy replacement for this.  Thanks.

**Comment by timmo001** [comment]
@mbrownnycnyc All these cards are as simple as adding a card with the `hass` type as you said, but the only difference is the screenshot increases the `width` and `height` of the card. This will allow the card to show the controls and extra info.

If you have any suggestions to improve the documentation, feel free to open a PR with your improvements. Thanks!

**Comment by mbrownnycnyc** [comment]
I just figured this out myself.  Sorry to have opened a ticket for it.  Thank you for the great solution!

**Comment by timmo001** [comment]
> I just figured this out myself. Sorry to have opened a ticket for it. Thank you for the great solution!

Np :+1:
