### ISSUE TITLE
Not pulling entities from Home Assistant when in edit mode.

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#216]
# Description

When using the UI to add items the entity ID is not populating as expected.  Running 0.87.1 of HA and latest home-panel.

## How to reproduce the issue (if applicable)

Add a new item, tested in both chrome and Safari on macOS. 

## Screenshots (if applicable)

![screenshot 2019-02-24 at 4 31 25 pm](https://user-images.githubusercontent.com/190136/53302023-bd3e6480-3851-11e9-85ea-dea26d3b6f6a.png)

**Comment by timmo001** [comment]
This was never a feature. The whole config UI is currently being rewritten. If you would still like this after the new UI, please open a feature request.
