### ISSUE TITLE
Sidebar items not displaying in Safari macOS

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#218]
# Description

When in editing mode the sidebar items are not displaying but they Are clickable if you however over the are. Using latest Home Panel.

## How to reproduce the issue (if applicable)

Go into editing mode on macOS Safari (12.0.1).
Tested in Chrome and are displayng and working.

## Screenshots (if applicable)

![screenshot 2019-02-24 at 4 30 51 pm](https://user-images.githubusercontent.com/190136/53302041-02fb2d00-3852-11e9-8aad-22c1a445cf6f.png)

**Comment by timmo001** [comment]
This will be removed in #199
