### ISSUE TITLE
Docs are gone

### ISSUE THREAD

**Issue by Fred-DTV** [timmo001/home-panel#2230]
### Description

Hi @timmo001 

Just a quick heads up: The link to the docs doesn't work anymore: https://home-panel.timmo.dev/docs/setup
Neither in the app nor here in the readme

**Comment by cengbrecht** [comment]
Can confirm I just tried to go there, looks like the cert for the io page backend is broken.

**Comment by Fred-DTV** [comment]
Still n/a

**Comment by jeffstearns** [comment]
Author contact email `contact@timmo.xyz` doesn't resolve either.
