### ISSUE TITLE
WebUI - clicking Cancel doesn't revert changes

### ISSUE THREAD

**Issue by benjgos** [timmo001/home-panel#227]
If you make changes and hit cancel, the changes are still applied.
Examples:
1. Add a new item, give it a name and click Cancel. the new item appears.
2. Delete an item, click Cancel, the item is deleted.
User would assume that clicking cancel would revert all changes.

Chrome 72 MacOS 10.14, Home-Panel latest docker from Mar 1st. assuming 0.70(?).

**Comment by benjgos** [comment]
Hi, I upgraded my docker image but still see this and the other issues that are now stated as fixed. Any way I can verify what version/build I have installed on my end?

**Comment by benjgos** [comment]
never mind found the issue. by default docker installs the 'latest' tag, but that was from 3 months ago. installed edge and I get the new edit UI. :)) looks great and I can't wait to get into it! thanks!!

Side note, might be a good idea to update the 'latest' tag or update the documentation to fetch 'edge' instead. Also, the documentation link on https://hub.docker.com/r/timmo001/home-panel is incorrect (directs to the old domain)

**Comment by timmo001** [comment]
Yes, please wait for the latest release, which I will be releasing soon.

The docs are there for the stable releases which are published when I tag a release.

**Comment by benjgos** [comment]
Understood, so I was just too excited to see the new stuff. :) I'll move to latest when it's officially released.
Also, If you could add a build/commit number somewhere, that would be great. If not the UI, than somewhere during start up. Possibly something like:
```
-----------------------------------------------------------
Home Panel (build...)
-----------------------------------------------------------
```
