### ISSUE TITLE
Adding a NestCam as a Camera doesn't show the Still URL

### ISSUE THREAD

**Issue by benjgos** [timmo001/home-panel#254]
When adding a Nest Camera all I see is a broken image in home-panel but clicking on the image opens up correctly.

I have both the Still URL and URL set the same:
Still URL: "http://192.168.1.40:8123/api/camera_proxy/camera.upstairs?api_password=XXXX”
URL: "http://192.168.1.40:8123/api/camera_proxy/camera.upstairs?api_password=XXXX”
When pasting the URL as is into a browser, it displays it correctly.

From sniffing the traffic i can see that the difference between the home-panel request for a still image and the home-panel request for the full image when clicked (URL) is what’s causing HASS to fail on authorization.
Still URL that fails authorization:
 GET /api/camera_proxy/camera.upstairs?api_password=XXXX?number HTTP/1.1
 Each request seems to increase the **number**. 
This URL also fails when pasted directly into a browser.
Clicked on image (URL) that fetches the image correctly:
 GET /api/camera_proxy/camera.upstairs?api_password=XXXX HTTP/1.1

I'm not sure why the number is added, but if there's a good reason to have it in, maybe it's worth making it optional.

**Comment by timmo001** [comment]
Try using an iframe instead. You might have better results

**Comment by benjgos** [comment]
Closer, but not quite there:
Left is the Camera entry, right is the iframe
<img width="815" alt="Screen Shot 2019-03-29 at 04 58 02" src="https://user-images.githubusercontent.com/232766/55224952-8ad0b000-51df-11e9-9508-28905e261261.png">

iframe config:
<img width="961" alt="Screen Shot 2019-03-29 at 04 58 26" src="https://user-images.githubusercontent.com/232766/55224997-a045da00-51df-11e9-8838-7096815e04c8.png">

I'm also thinking there might be a bug around iframe height, but I didn't test with different iframe entries.

**Comment by benjgos** [comment]
Quick update: Height for iframe doesn't seem to work on other url's either.
<img width="953" alt="Screen Shot 2019-03-29 at 05 24 14" src="https://user-images.githubusercontent.com/232766/55226422-f7997980-51e2-11e9-9e10-c33e603a9c33.png">

<img width="420" alt="Screen Shot 2019-03-29 at 05 27 10" src="https://user-images.githubusercontent.com/232766/55226594-5959e380-51e3-11e9-8475-5245f5c52ae8.png">

**Comment by timmo001** [comment]
Unfortunately, iframes are strife with issues, since you rely on the page you are trying to contain will scale appropriately. This is not fixable.

The height issue, however, can be fixed. :smiley:

**Comment by timmo001** [comment]
Typo found for height. This will be in the next release

**Comment by benjgos** [comment]
Awesome, thanks! 
So only question now is about the camera view (sorry for mixing bugs in here).
Is there a way to remove or make optional the "?number" part of the URL when fetching the Still URL?
That would provide in the case of Nestcams a resized still image and have it clickable for a larger image.
