### ISSUE TITLE
Tapping anywhere shows the top menu and the page bar

### ISSUE THREAD

**Issue by benjgos** [timmo001/home-panel#255]
Tapping on any item pulls down the top config bar and the bottom page bar.
This also happens if you just tap own the background.
This also happens on desktop if you move your mouse, but on a tablet it shifts the whole view, pops up scroll bars (if it's now too large to fit the screen) and makes everything a little slower.
Might be useful to make this configurable and add a little button to pop up the menus

Testing on amazon Fire 7 using Fully Kiosk Browser. Home-Panel Edge docker from Mar 29th

**Comment by timmo001** [comment]
This is intended

**Comment by benjgos** [comment]
Any chance to make it configurable? or possibly, float the top and bottom menu above the rest of the page (unless you go into edit mode for example)? that way things don't resize and move around every time. This would probably make it smoother.
