### ISSUE TITLE
Bottom bar seems to take a lot more room than it's visible hight.

### ISSUE THREAD

**Issue by benjgos** [timmo001/home-panel#256]
The bottom page bar seems to take up more room (in hight) than the visible bar size
This is very clear on small screens (tablet) when the bottom bar pops up, cuts the bottom (3rd) row, and causes scroll bars to show up.
Example:
![Screenshot_2019-03-29-21-49-42](https://user-images.githubusercontent.com/232766/55270617-f01fb200-526e-11e9-8508-5ef017e14c79.png)

Amazon Kindle 7 using Fully Kiosk Browser 1.30.

**Comment by timmo001** [comment]
This will disappear after a few seconds. I do not see any solution to this.
