### ISSUE TITLE
Card/Group Ordering

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#259]
# Description

Add support to change the position of the cards. This could be via a button or a drag library like the one below.

## Additional

https://haltu.github.io/muuri/

<blockquote><div><strong><a href="https://haltu.github.io/muuri/">Muuri - Responsive, sortable, filterable and draggable grid layouts</a></strong></div><div>Muuri is a JavaScript library that creates responsive, sortable, filterable and draggable grid layouts.</div></blockquote>

**Comment by aptonline** [comment]
Can you add page ordering to the list too :)

**Comment by timmo001** [comment]
Just realised I opened the same issue as the one I opened before:

https://github.com/timmo001/home-panel/issues/241
