### ISSUE TITLE
I can't find the Webapp

### ISSUE THREAD

**Issue by agrigo2s** [timmo001/home-panel#275]
Hi,
i was trying to install the everything but there is no link for the webapp. 

https://timmo.dev/home-panel/setup/

<blockquote><img src="../favicon.ico" width="48" align="right"><div><strong><a href="https://timmo.dev/home-panel/setup/">Setup - Home Panel Docs</a></strong></div><div>A touch-compatible web-app for controlling the home</div></blockquote>

**Comment by timmo001** [comment]
More information required. Please state which method you are using and what the issue is.

You should be able to access the app at `YOUR_IP:8123` (by default)
