### ISSUE TITLE
On click action of automation entity

### ISSUE THREAD

**Issue by psoemmer** [timmo001/home-panel#288]
# Description

**Problem/Motivation**
Need to switch automations on/off in Home Panel

**Expected behavior**
On click action of an automation widget: toggle on/off

**Actual behavior**
On click action of an automation widget: nothing?

**Steps to reproduce**
add an automation to home panel an try to switch the state

**Proposed changes**
Change the action of the widget

**Comment by timmo001** [comment]
Support for automations added.

Will be in the next release :smiley:
