### ISSUE TITLE
Group names not displaying on page

### ISSUE THREAD

**Issue by b3tts32** [timmo001/home-panel#316]
# Description
Group names are not displaying for new or existing 

## How to reproduce the issue (if applicable)
Open up home-panel homepage or add a new page then add a new group

## Screenshots (if applicable)

![Screenshot from 2019-06-12 20-54-19](https://user-images.githubusercontent.com/13155633/59398049-5b4c3100-8d54-11e9-8cdb-f50621e1a149.png)

## Additional information
I tried copying the starter template from the documentation website and I get the same behavior. Tried in both Chrome and Firefox only to get the same behavior. I'm using the docker non ssl version of the app

**Comment by timmo001** [comment]
The app has been updated to the new major version which. Please read the release notes, upgrade and try again. Reopen if your issue is still unresolved.
