### ISSUE TITLE
Required to double click on tablets

### ISSUE THREAD

**Issue by Dmurph24** [timmo001/home-panel#381]
# Description
On a tablet you are forced to double click in order to press a tile. This is because there is no mouse and the web app does not "wake up" until pressing the screen first.

## How to reproduce the issue (if applicable)
I used an iPad, but i would imagine it would be reproducible with any tablet

## Screenshots (if applicable)
N/A

## Additional information
Was not sure wether to categorize this as a bug or feature request because it might be both.

**Comment by timmo001** [comment]
The app has been updated to the new major version which. Please read the release notes, upgrade and try again. Reopen if your issue is still unresolved.
