### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by TheCellMC** [timmo001/home-panel#42]
## Description
It would be nice if we could split tiles into multiple pages to clean up the interface. The navigation bar could be composed of MDI icons and could be on the left side or on the bottom.

**Comment by timmo001** [comment]
A mobile stepper may be of use here: https://material-ui.com/demos/steppers/#mobile-stepper

**Comment by aptonline** [comment]
Would also be nice to add animations between pages.

**Comment by timmo001** [comment]
Done! Will be available in next stable release
