### ISSUE TITLE
Time/Date clipped on mobile

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#474]
Using v2.0.0 of home-panel the date/time is clipped when viewing in mobile.

![259235D1-8A23-4381-A34D-B7B442B4ACD9](https://user-images.githubusercontent.com/190136/64918185-c1e94c80-d792-11e9-9983-73ec925f856f.jpeg)

**Comment by timmo001** [comment]
Do you have autohide toolbar enabled in this image?

**Comment by aptonline** [comment]
I tried it with and without auto-hide on. Same issue. Can’t now change as configuration not working due to other reported bug.

**Comment by aptonline** [comment]
Confirmed resolved in 2.0.2
