### ISSUE TITLE
White/blank page when opening configuration page

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#476]
When going to configuration page after editing theme nothing loads and I get a white/blank page .

After editing a custom theme I refreshed the page and the screen wouldn't load getting the above issue.

I deleted the `config.db` which then allowed the main page to load display but when attempting to visit the configuration page again I got the same issue.  Cleared cache and same problem.

**Comment by aptonline** [comment]
Any update on this issue?

**Comment by timmo001** [comment]
Not in the last 2 hours of free time i've had.

What is your browser, os, device etc. so I can help to resolve your issue.

**Comment by aptonline** [comment]
Safari on Mac Mojave. Also tried in Chrome and same issue. Worked fine before editing the theme and once I refreshed it seemed to get ‘stuck’ just displaying the white screen.

**Comment by timmo001** [comment]
Odd.. What version is safari?

**Comment by aptonline** [comment]
Safari 12.1 and Chrome 76.0.3809.132.

I've deleted the container and downloaded latest version 2.0.2 to test.  Issue resolved but will keep an eye on things.
