### ISSUE TITLE
Entities - Control volume of media player

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#482]
# Description

Input number to control volumes etc

**Comment by thundergreen** [comment]
ItÄs not only volume for entites but also zoom function etc.

**Comment by timmo001** [comment]
I've decided that this feature would not fit the design of the app. The current volume control works fine and is in line with the HA spec.

![image](https://user-images.githubusercontent.com/28114703/65790519-b82ef400-e157-11e9-9293-208940316755.png)

**Comment by thundergreen** [comment]
But it's not about volume control @timmo it's about more stuff to control .
Pity but okay .. I'll have to accept  thanks anyway

Timmo <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 19:50:

**Comment by thundergreen** [comment]
Sorry to come back to this issue again but I really miss input_numer as it also serves for other things like Camaera. Volume of Alarm sounds, Zoom, Move cam  etc. Might be worth to re-think about this feature integration.

**Comment by timmo001** [comment]
You mean the `input_number` integration in HA. Not to control volume in a `media_player` integration which already exists. I will create a new issue on this.
