### ISSUE TITLE
speedtest sensors not available in homepanel 

### ISSUE THREAD

**Issue by nocturneop15** [timmo001/home-panel#499]
When creating new card in hompanel, I can see all sensors/switches I have in my Homeassistant, except speedtest:
sensor.speedtest_download
sensor.speedtest_upload
sensor.speedtest-ping

those mentioned above are not available in drop-down menu in card settings.

HassOS 2.12
Homepanel 1.0.4
Home Assistant 0.98.5

**Comment by timmo001** [comment]
Not sure why. The websocket is the exact same one that HA's frontend uses. Are you sure they show up in `<yourhaurl>/developer-tools/state`?

**Comment by nocturneop15** [comment]
I found that speedtest sensors are not available in drop-down menu, but when I start writing their name, they appeared. Looks like they are just behind limit of number of items that are available in drop-down menu. 

Please close this as it is not really an issue.

**Comment by timmo001** [comment]
There is a limit to this list that appears due to the visual lag that occurs with the amount of entities.

The idea is that you should type the partial name, which will filter down for you to be able to select the one you want, so what you are seeing is expected.
