### ISSUE TITLE
Changing Background color leads to blank screen

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#520]
# Description

Once I change the background color. It leads to a blank configuration screen. Not sure if it is really just the background color. I took a screenshot of Chrome Console Errors:

## How to reproduce the issue (if applicable)

CHange background Color in Configuraton for the theme

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/13320319/65408681-29804700-dde6-11e9-8e66-d10acbe807a0.png)

**Comment by thundergreen** [comment]
Also adding background image ends up in


![image](https://user-images.githubusercontent.com/13320319/65409162-479a7700-dde7-11e9-8644-28e547ee84b4.png)


Themes are deleted

![image](https://user-images.githubusercontent.com/13320319/65409185-58e38380-dde7-11e9-995d-0cbce6460af6.png)

**Comment by thundergreen** [comment]
Hi there. Unfortunately I face this issue again and again. SO far it is not possible to change the background color (nor background image). I let this untouched for the moment but yould highly appreciate this to work.

**Comment by timmo001** [comment]
Fixed in #584
