### ISSUE TITLE
Home assistant configuration lost after sign out

### ISSUE THREAD

**Issue by max-rh** [timmo001/home-panel#545]
# Description
Once logged in to the home panel and configure the connection to home assistant; its successful but once i log out from the home panel and re log in again, the connection to HA is lost and i have to configure it again.

## How to reproduce the issue (if applicable)
The issue happens at each login 

## Additional information

Thanks for such a great panel, been looking for a while for a nice elegant dashboard; and this is by far the most elegant.

**Comment by timmo001** [comment]
This is expected. The idea of this is so you can log in to another instance of Home Assistant under another user.

A log out will log you out of all sessions in the app.

**Comment by johntdyer** [comment]
Hrm, I only have one user and I am constantly logged out.. Its rather annoying to be honest

**Comment by TheCellMC** [comment]
I second that. I do not believed that many people run multiple multiple instances of HA. I would prefer this to be opt-in through a settings option.
Every time I want to open the panel on a different device, I have to sign in 3 times (once for HA, once for the panel (I am using Hass.io ingress) and once for the panel to connect to HA). Honestly, this is rather annoying.

**Comment by timmo001** [comment]
You do stay logged in, so long as you do not log out of the app. Staying logged in between different sessions is not a good idea. It takes 10 seconds to log back in if you are switching between users
