### ISSUE TITLE
Add Values to graphs 

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#548]
# Description

I added some graphs but they are almost nonsense, as I can't see any value on y-axis

Adding those values would give an idea of the graph

## Suggested Actions

Add value to graphs

## Additional
here a screenshot of my systemstats, which don't mean anything so far..

![image](https://user-images.githubusercontent.com/13320319/65971062-e407ed80-e467-11e9-91c6-09086820a777.png)

**Comment by thundergreen** [comment]
Nice would be maybe also the timestamp if this is possible. Like this "debigging" is better. I think of systemstats where sometimes peaks are shown. I use last 24 hours as time range. If possible .. then ir could be a mouse - info or something.

**Comment by thundergreen** [comment]
The best would be X-Axis=timeline and Y-Axis= value i guess

**Comment by thundergreen** [comment]
Not bad! BUT i am missing the time axis somehow to understand the graph better.

**Comment by timmo001** [comment]
The aim of Home Panel is to show a brief summary of data. If you want to go into this kind of detail, please use applications like inlfuxdb and/or grafana which have the facility to store this amount of data.
