### ISSUE TITLE
No valid ingress session

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#554]
# Description
Since I anstalled >HomePanel I get ```No valid ingress session``` in my logs and my touchscreen which is directly attached to my hassio machine goes black. Mouse cursor is still there but nothing would react.

## How to reproduce the issue (if applicable)
Let HomePanel run for a while and you will get this black screen

## Additional information

I will now deactivate the HomePanel Addon to narrow down if it is indeed HomePanel Issue

**Comment by timmo001** [comment]
Since this is an issue for the add-on, please open a new issue there:

https://github.com/hassio-addons/addon-home-panel/issues
