### ISSUE TITLE
Smaller resolution grid issue

### ISSUE THREAD

**Issue by michaeldavie** [timmo001/home-panel#558]
# Description

2.2.1 introduced scroll bars on a 1024x600 screen that were not present in 2.2.0.

## Screenshots (if applicable)

2.2.0

![Screenshot_20190928-180107](https://user-images.githubusercontent.com/16008714/66093683-44c62180-e55f-11e9-99f5-88519289ca64.png)

2.2.1

![Screenshot_20190929-142346](https://user-images.githubusercontent.com/16008714/66093694-4db6f300-e55f-11e9-8585-fb675f60e1a5.png)

**Comment by timmo001** [comment]
Scrollbars were always there. It just seems that the layout is scaling the grids for your lower resolution.

**Comment by michaeldavie** [comment]
Right, but something changed between these two versions that caused them to be always visible. I think that it looked better when they were hidden in the resting state, as in 2.2.0.

**Comment by timmo001** [comment]
That was never a thing, but I like the idea!

**Comment by michaeldavie** [comment]
I'm afraid that #583 didn't resolve this issue, the behaviour introduced in v2.2.1 is still present in v2.3.0.

**Comment by timmo001** [comment]
> I'm afraid that #583 didn't resolve this issue, the behaviour introduced in v2.2.1 is still present in v2.3.0.

Did it help at all? Can you post an updated screenshot?

**Comment by michaeldavie** [comment]
No, still the same. Here's a shot with 2.4.0 (it's harder to take screenshots as the tablet has now been mounted).

![2 4 0](https://user-images.githubusercontent.com/16008714/66276358-2e221200-e860-11e9-9abc-160f0869cc81.jpg)

**Comment by timmo001** [comment]
Odd.. I have not got a device with your resolution specifically, but emulating the screen size with chrome for me has no sizing issues

![image](https://user-images.githubusercontent.com/28114703/66276432-ed8bbe00-e88a-11e9-845f-384324fbd3df.png)

Try enabling dense toolbar / auto hide toolbar in configuration, so you will at least have more screen real estate to use

![image](https://user-images.githubusercontent.com/28114703/66276456-33e11d00-e88b-11e9-9ceb-82abc6f5c788.png)

**Comment by michaeldavie** [comment]
Yes, I'm running 2.4.0. For some reason I can't get the dense or auto-hide options to stick, though they did in the past, so I'm unable to test this option.

When I emulate a 1024x600 resolution in Chrome I see the same issue, so maybe it's something to do with my layout? As I said above though, the issue manifested between 2.2.0 and 2.2.1.

<img width="1097" alt="Screenshot 2019-10-06 19 20 09" src="https://user-images.githubusercontent.com/16008714/66277603-c32c0780-e86e-11e9-9f4a-cdbb18285676.png">

**Comment by timmo001** [comment]
Figured out your issue.

![Screenshot_20191007-093724](https://user-images.githubusercontent.com/28114703/66300000-7424b780-e8ec-11e9-84e4-79bfe3997b5c.jpg)

When you switch off both the time and date the while UI shifts upwards. This can be adjusted.
