### ISSUE TITLE
19-10-04 06:52:30 WARNING (MainThread) [hassio.api.ingress] No valid ingress session d05991b3b6edcbd22413040d211e303709f296040e9c656d66f9eea26cbef1fa752fc9360e1be2bb669adc8e786d9a484431b70b031172f20869a4d4e14ecfb7

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#577]
# Description

plese see 

https://github.com/hassio-addons/addon-home-panel/issues/38

**Comment by thundergreen** [comment]
@Frenck asked me to open issue here :/

**Comment by timmo001** [comment]
Please do not duplicate issues. Especially when you have already opened them in the relevant repository.
