### ISSUE TITLE
Open RSS Feed in a pop-up.

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#610]
# Description
Opening the rss feed leads to open a new tab in my chrome browser. According to the design of the dashboard it runs in fullscreen mode on my touchscreen. Opening the rss feed in a new tab will break this design as I will be oblidged to deactivate fullscreen- mode and close the opened external feed tab to get back to the dashboard

## Suggested Actions

open rss feed in pop-up.

## Additional

Please indicate RSS feed fromats in config line.

**Comment by timmo001** [comment]
I'm not a fan of adding pop up functionality to the app. The main reasons for this is:

- Popups are an annoyance
- Popups are blocked in most browsers
- Opening with `target="_blank` is a preferred standard

**Comment by thundergreen** [comment]
But how would be wrchive that a new wondow is oopened and kills the possibility to go back to the dashboard once opened? I understand your point of view but was wonderung how to solve this problem then.

**Comment by timmo001** [comment]
This would not be possible since most websites prevent the use of an iframe to show their site (especially news sites)

**Comment by thundergreen** [comment]
OK.. this answers my question. Thanks a lot anyway and Congratulations! your dashboard is really really good. I hope I am not too annoying to bother you with feature requests but each time I build and rebuild my dashboard I got new ideas :) And you almost implemented all of them.. That's so crazy cool! Big Big Thanks to yu and I hope you will be able to keep going with this project.
