### ISSUE TITLE
add Persistant Notifications

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#621]
# Description

I'd like having something like a reminder function. system eror etc. as Persistant messages. I think of garbage collection. Birthda reminder etc. Would be nice wouldn't it? Of course with dismiss function like in hass

## Suggested Actions

Persistant message from home assistant has been triggered and will show up in a widget. Possibility to dismiss. If no persitant message available then just show something like: "No events"

**Comment by timmo001** [comment]
Not sure whether this is viable or in scope for the app since the point of home panel is to be a frontend. Automations are not for this app, which you are suggesting, they are for applications like Home Assistant which we integrate with.

**Comment by timmo001** [comment]
I may revisit this idea in the future but for now I will have to decline as it is out of scope
