### ISSUE TITLE
ADD vertical input number

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#625]
# Description

By creating my dashboard I relized that it would be great having a input_number in vertical style. Either it becomes vertical by chosing the dimensions of the widget or may by selecting an option.

**Comment by timmo001** [comment]
Can you create a mockup of this? I'm imagining an input box rotated in my head.... 😕

**Comment by thundergreen** [comment]
I was wondering if the widget just couldn't behave logocally. Means. If i have an input_number (lets call it slider) which is visible at 2X1 . This way it would show up horizontal (width x height). If I define 1x2 means the widget is automaticcally turned into vertical position. I have an Android App which does that (HomeHabit) That'S why I ask.

**Comment by timmo001** [comment]
I have absolutely no idea of what you are requesting.

Please reopen if you have an example (preferably with screenshots) of what you are requiesting. Width and height of cards are both configurable here.

**Comment by thundergreen** [comment]
For the moment we can only make horizontal input_numbers :
![image](https://user-images.githubusercontent.com/13320319/66397340-e0321900-e9db-11e9-8f07-ae51ade7c41e.png)


I'd Like having those input_numbers also vertical like this:

![vertical input_number](https://user-images.githubusercontent.com/13320319/66397507-4323b000-e9dc-11e9-8746-d51761dcbe51.JPG)

**Comment by thundergreen** [comment]
I'd use this for volumes and also lights

**Comment by thundergreen** [comment]
May I aske why  this isuue has been closed?
