### ISSUE TITLE
ADD group widget

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#626]
# Description

Sometimes it's nice having multiple entities in one group like temperature pressure and humidity to save space and make it more readable

**Comment by timmo001** [comment]
This is already possible. Use `group.myamainggroup` from HA

**Comment by thundergreen** [comment]
Wanted to group myself. But if it's possible. I'll try and create the groups i need accordingly..

**Comment by thundergreen** [comment]
Groups not working:

![image](https://user-images.githubusercontent.com/13320319/66390640-5d08c700-e9cb-11e9-8be8-b100ae9495d2.png)
