### ISSUE TITLE
Documentaton - Configuration - Cards/Groups/Pages

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#630]
# Description

The old docs were pretty detailed with gifs showing what can be done and how to do it.

Add docs (with images/gifs) for configuring cards, groups and pages.

**Comment by timmo001** [comment]
Should use the default theme when taking screenshots / gifs

**Comment by PurelyNicole** [comment]
I've forked the branch to begin work on this. Do the old docs exist anywhere?

**Comment by timmo001** [comment]
> I've forked the branch to begin work on this. Do the old docs exist anywhere?

Look at older tags on this repo for <v1.0.0
