### ISSUE TITLE
Documentaton - Showcase

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#631]
# Description

Starting up a showcase of what can be done with the app would be nice. There would need to be a set standard (comply with markdown rules, format in one way etc.). This should include screenshots, how to replicate etc. 

An example would be the Home Assistant demo, which showcases the UI:

<https://demo.home-assistant.io>

**Comment by thundergreen** [comment]
I'd apply for this. I can send you some screenshots if you want. Also if needed step by step explanation with smaller images?
