### ISSUE TITLE
Climate not turning off

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#634]
# Description

I tested the climate widget. All modes are correctly but turning off won't turn it of. I could see a nillisencond that the climate has been turned off but directly on to the last setting.

I made a step by step recording attached to this issue.

If I turn off the climate via home assistant it reflects the right mode off but turning off in the widget does not work

## How to reproduce the issue (if applicable)

add climate to homepanel and try to turn off

## Screenshots (if applicable)
[climate not turning off.zip](https://github.com/timmo001/home-panel/files/3702522/climate.not.turning.off.zip)

**Comment by thundergreen** [comment]
Did you get the time to watch into this ?

**Comment by timmo001** [comment]
Unable to reproduce
