### ISSUE TITLE
Tweak for cover support

### ISSUE THREAD

**Issue by xbmcnut** [timmo001/home-panel#639]
# Description
Love what you've done in v2 but I'm trying to replicate my other dashboards in HP and two important tiles for the wife are the garage door and the front door lock.
![image](https://user-images.githubusercontent.com/1492137/66436041-a0723c80-ea82-11e9-9526-1acfdd311aef.png)

## Suggested Actions
It would be great if the covers and locks could show padlocks; an unlocked one for unlocked/open and a locked one for locked/closed. Touching the icon toggles the state. Furthermore, being able to customize the icons would be hugely beneficial; green for locked and red for unlocked.
![image](https://user-images.githubusercontent.com/1492137/66436059-a9630e00-ea82-11e9-9b40-e22090f25b1b.png)

**Comment by timmo001** [comment]
Just add an icon to the card. This will be just `lock` in the icon config
