### ISSUE TITLE
Allow control of icon sizes or auto scale to screen

### ISSUE THREAD

**Issue by xbmcnut** [timmo001/home-panel#64]
As you can see on my Lenovo Tab 8", although it looks great, not much room for too many icons. Would be great to be able to scale the header, font and or tile sizes somehow.

![image](https://user-images.githubusercontent.com/1492137/44895194-5e3adf80-ad47-11e8-8273-e6586f2b50e9.png)

**Comment by timmo001** [comment]
Is this your device? https://www.lenovo.com/gb/en/tablets/android-tablets/tab-4-series/Lenovo-TB-8504/p/ZZITZTATB08

Quite a shallow resolution to work with. I have already done the best I can with the shrinking the resolution and text on certain screen sizes. I'm betting your device is that odd resolution and DPI that scales poorly on most sites too...

**Comment by timmo001** [comment]
One recommendation I would have is to ask for the desktop page / desktop version via your browser settings. For some reason, the 'mobile' version scales the page to allow for a portrait screen.

**Comment by xbmcnut** [comment]
Thanks. Desktop mode made portrait mode quite a bit better but unfortunately Chrome does not save this setting when "adding to Home Screen". Landscape mode it made little difference. And yes, that is my device.

**Comment by timmo001** [comment]
Unfortunately, your device falls in the "I am a tablet, but use the resolution / DPI of a phone" category. There is nothing I can change to reduce the size of any of the UI elements any further than they already are.
