### ISSUE TITLE
Stupid questions sorry

### ISSUE THREAD

**Issue by xbmcnut** [timmo001/home-panel#641]
# Description
Hi. Sorry, but what does 'elevation' and 'square' do? Can't seem to see what they do.

**Comment by thundergreen** [comment]
Elevation makes shadow around the box and square activated removes the round corners of the widget

**Comment by xbmcnut** [comment]
Thanks. The background tile combo I'm using must not be 'elevation' friendly as the effect is not visible. See the square working.
