### ISSUE TITLE
RSS No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#650]
# Description

When adding a RSS feed I get this error message:

```
Access to fetch at 'https://ttv2.myamity.info/rss.php?cat=3,54,50,52,8&dllink=1' from origin 'http://home-assistant:8234' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
asyncToGenerator.js:6 Uncaught (in promise) TypeError: Failed to fetch
```

## How to reproduce the issue (if applicable)

add RSS widget and add this link:

```https://ttv2.myamity.info/rss.php?cat=3,54,50,52,8&dllink=1```

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/13320319/66602310-20df8d00-ebaa-11e9-9568-fcfbb74488e7.png)

**Comment by timmo001** [comment]
This is not an issue with the app.

The error is from the site you are trying to use which does not allow requests correctly
