### ISSUE TITLE
Use device class for state

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#662]
# Description

I have a bunch of window and door sensosrs. For the moment unfortunately it's only possible to see on or off state instead of opened or closed according to device class. Maybe it's possible to add device classes to sensors with sensor state icons?

## Suggested Actions

Maybe state mapping would be possible? Or state icons?

**Comment by timmo001** [comment]
Adding icons would not work, but using the device_class might be possible

**Comment by thundergreen** [comment]
I meant more like:

is sensor off --> icon a if sensor on --> icon b
