### ISSUE TITLE
Subscribe to config updates from feathersjs

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#663]
# Description
I use an attached toucschreen without any mouse or keyboard attached to the intel NUC running hass and homepanel. The problem is that dashboard will never be updated after making changes (e.g remotely via laptop.)

The "old" dashboard is still persistent and i have to kill chrome process each time or use VNC to refresh the dashboard. It's a kind of annoying.

**Comment by timmo001** [comment]
The app should actually subscribe to updates on the config as it did in the last major version

**Comment by thundergreen** [comment]
It does after re-log-in but not "on-the-fly" .
