### ISSUE TITLE
Allow rounded corners for cards

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#67]
The custom theme funtionality  is great but I would like more control. The ability to set corner radius or transparency for example.

The ability for home-panel to read a `custom.css` file located in the config directory would be a great addition.

**Comment by timmo001** [comment]
`The ability to set corner radius or transparency`

This can be added, but a custom css file is too much. There are browser extensions that can do this if this is what you want to do.

The idea of the themes and config file is to allow the user to set these options without having to mess with stylesheets etc.

**Comment by timmo001** [comment]
Also, transparency should already work. If you add the alpha channel to the hex code of the card color etc.

`"on": "#RRGGBBAA"`

**Comment by timmo001** [comment]
Added. Will be in the next release
