### ISSUE TITLE
Edit Card layout issue in Safari

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#672]
When editing a card on Safari (12.1) on macOS here is some inconsistencies between the layout on safari and say between chrome.  This stops being able to search for entities within Safari.

See the attached images:

![Screenshot 2019-10-14 at 22 16 33](https://user-images.githubusercontent.com/190136/66783779-8eecc280-eed0-11e9-8c0b-e401a3d0aa16.png)
Safari.

![Screenshot 2019-10-14 at 22 16 23](https://user-images.githubusercontent.com/190136/66783791-9744fd80-eed0-11e9-8d01-0944fc44cca7.png)
Chrome.

**Comment by timmo001** [comment]
I feel like this is a bug in safari itself with `flex` layouts.

Either that, or it is an issue that cannot be fixed here since the `Grid` layout is from Material UI
