### ISSUE TITLE
Warm Colour Presets and Colour Temperature Slider

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#68]
Add warm hue colours to the choice of presets.  Also a colour temperature slider similar to HA.

**Comment by timmo001** [comment]
`Add warm hue colours to the choice of presets`

Can you expand on this?

**Comment by aptonline** [comment]
As per the home assistant UI. The slider and also the actual colours for quick access?

![screen shot 2018-09-01 at 5 06 43 pm](https://user-images.githubusercontent.com/190136/44947720-7ffc9b00-ae09-11e8-9934-6d1ca13bbcf5.png)

**Comment by timmo001** [comment]
The material-ui slider component does not support backgrounds. Also, I do not like the way the hass temp slider looks. The functionality is still the same.

There are no good color pickers out there. The hass slider was custom and was designed for Polymer, not ReactJS. The way it is now with predefined colors from a swatch will suffice. The swatches are much easier to use on touch devices also

**Comment by aptonline** [comment]
Ok so slider no but adding the colours are needed. The current colour choices are limited.
