### ISSUE TITLE
Light slider turns off light

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#682]
# Description

I have a couple of z-wave dimmer around my house. I added such entity_id to my dashboard and tried to adjust the brightness. The first attempt works well.. the light turn to the seet brightness. But increasing or decreasing my light with the slider will turn off the light entirely.

## How to reproduce the issue (if applicable)

add light widget --> play with the slider --> light turn of by changing the brightness by the slider a second time

**Comment by timmo001** [comment]
Cannot reproduce. Tried with multiple lights. Lights stay on
