### ISSUE TITLE
Group with lights not working

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#683]
# Description

I'd like to put some lights in a group and control them via widget with the brightness slider like for light entites.

But first when I add a group.light_xxx the widget is empty and no slider or anything else is inside.

## How to reproduce the issue (if applicable)

add widget --> chose group.light_xxxx --> widget is emty

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/13320319/66993359-ba87cc80-f0cb-11e9-94d9-f9ee3f108abe.png)

## Additional information

How is it suppsed to work? I use a mix of hue and zwave lights (dimmers) in those group

**Comment by timmo001** [comment]
I have absolutely no idea what you are on about.

![image](https://user-images.githubusercontent.com/28114703/67040454-6f95a580-f11b-11e9-8bae-a452c7d74255.png)

Groups act like switches. If you want to control multiple lights, create a light group
