### ISSUE TITLE
Light widgets mixed up

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#684]
# Description

I added a Zwave dimmer light (led strip) and a hyperion component light widget.

Now by changing the color in LED strip widget it changes color of hyperion widget. brightness of the led strip works well.

## How to reproduce the issue (if applicable)

add two lights with color pallette and change the color of one of the widget and you will see the color of the first widget will be changed.

**Comment by timmo001** [comment]
Unable to reproduce myself. If you manage to reproduce the issue, please post how.

Otherwise, please close

**Comment by thundergreen** [comment]
I will close this issue as it did not appear again. Will re-open if necessary
