### ISSUE TITLE
Configure media_player leads to blank screen

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#688]
# Description

I tried chaning the width of the media_player widget and got blank screen.

## How to reproduce the issue (if applicable)

add media_player widget --> change width to 3 --> blank screen

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/13320319/67113043-e2b12180-f1d8-11e9-9490-b6cf339ae5a4.png)

**Comment by thundergreen** [comment]
Also if my TV is off I get this:

![image](https://user-images.githubusercontent.com/13320319/67114142-81d71880-f1db-11e9-88c7-55aa67ff1669.png)


I think it's better to have either no pic call or maybe a standard one

**Comment by timmo001** [comment]
Looks like you don't have a `source_list` for that entity. Need to add a check for if this exists before rendering the select
