### ISSUE TITLE
Add version number to front end

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#690]
Due to the fast pace of updates I sometimes forget which version of Home-Panel I'm running, would it be possible to add a version number to the configuration panel, maybe at the bottom?

**Comment by timmo001** [comment]
I'm not going to do this. This will have to be automated and stored in a file to read somewhere otherwise, it will be hardcoded and never changed.

Unless someone has a way to do this, perhaps at build time in the CI, please open a PR, but in the meantime I will close this issue
