### ISSUE TITLE
RSS feed Not Working

### ISSUE THREAD

**Issue by TheCellMC** [timmo001/home-panel#694]
# Description
First of all, thanks for the amazing work.
So I'm running Home Panel on Hass.io on an Intel NUC and I'm access it through Hass.io Ingress. Sadly, I'm not able to get the RSS feed to work. All I get is a red box.

Here is the feed I entered: http://feeds.bbci.co.uk/news/rss.xml

## Screenshot
 
![Screenshot 2019-10-20 at 16 35 41](https://user-images.githubusercontent.com/12169936/67161141-ee772200-f357-11e9-80fc-637e19f5af9e.png)

## Log

Here are the related errors which appear in the Safari developer tools:
```
[Error] Not allowed to request resource
	(anonymous function) (2.229d9a41.chunk.js:1:1405406)
	(anonymous function) (2.229d9a41.chunk.js:1:1404336)
	(anonymous function) (2.229d9a41.chunk.js:1:473312)
	k (2.229d9a41.chunk.js:1:633326)
	(anonymous function) (2.229d9a41.chunk.js:1:636321)
	(anonymous function) (2.229d9a41.chunk.js:1:636401)
	(anonymous function) (2.229d9a41.chunk.js:1:1407366)
	(anonymous function) (2.229d9a41.chunk.js:1:816695)
	(anonymous function) (2.229d9a41.chunk.js:1:1399398)
	initializePromise
	Promise
	value (2.229d9a41.chunk.js:1:1399376)
	u (2.229d9a41.chunk.js:1:1080248)
	(anonymous function) (2.229d9a41.chunk.js:1:1080033)
	r (2.229d9a41.chunk.js:1:327609)
	s (2.229d9a41.chunk.js:1:327812)
	(anonymous function) (2.229d9a41.chunk.js:1:327871)
	initializePromise
	Promise
	(anonymous function) (2.229d9a41.chunk.js:1:327763)
	(anonymous function) (main.ace29e53.chunk.js:1:136760)
	rs (2.229d9a41.chunk.js:1:1032708)
	Tc (2.229d9a41.chunk.js:1:1058108)
	(anonymous function) (2.229d9a41.chunk.js:1:1078079)
	sc (2.229d9a41.chunk.js:1:1042432)
	sc
	(anonymous function) (2.229d9a41.chunk.js:1:1001582)
	(anonymous function) (2.229d9a41.chunk.js:1:1078079)
	Go (2.229d9a41.chunk.js:1:1001529)
	$o (2.229d9a41.chunk.js:1:1001464)
	nc (2.229d9a41.chunk.js:1:1039229)
	ya (2.229d9a41.chunk.js:1:1018324)
	ya
	(anonymous function) (main.ace29e53.chunk.js:1:165353)
	u (2.229d9a41.chunk.js:1:1080248)
	(anonymous function) (2.229d9a41.chunk.js:1:1080033)
	r (2.229d9a41.chunk.js:1:327609)
	s (2.229d9a41.chunk.js:1:327812)
	promiseReactionJob
[Error] Fetch API cannot load http://feeds.bbci.co.uk/news/rss.xml due to access control checks.
	(anonymous function) (2.229d9a41.chunk.js:1:1405406)
	(anonymous function) (2.229d9a41.chunk.js:1:1404336)
	(anonymous function) (2.229d9a41.chunk.js:1:473312)
	k (2.229d9a41.chunk.js:1:633326)
	(anonymous function) (2.229d9a41.chunk.js:1:636321)
	(anonymous function) (2.229d9a41.chunk.js:1:636401)
	(anonymous function) (2.229d9a41.chunk.js:1:1407366)
	(anonymous function) (2.229d9a41.chunk.js:1:816695)
	(anonymous function) (2.229d9a41.chunk.js:1:1399398)
	initializePromise
	Promise
	value (2.229d9a41.chunk.js:1:1399376)
	u (2.229d9a41.chunk.js:1:1080248)
	(anonymous function) (2.229d9a41.chunk.js:1:1080033)
	r (2.229d9a41.chunk.js:1:327609)
	s (2.229d9a41.chunk.js:1:327812)
	(anonymous function) (2.229d9a41.chunk.js:1:327871)
	initializePromise
	Promise
	(anonymous function) (2.229d9a41.chunk.js:1:327763)
	(anonymous function) (main.ace29e53.chunk.js:1:136760)
	rs (2.229d9a41.chunk.js:1:1032708)
	Tc (2.229d9a41.chunk.js:1:1058108)
	(anonymous function) (2.229d9a41.chunk.js:1:1078079)
	sc (2.229d9a41.chunk.js:1:1042432)
	sc
	(anonymous function) (2.229d9a41.chunk.js:1:1001582)
	(anonymous function) (2.229d9a41.chunk.js:1:1078079)
	Go (2.229d9a41.chunk.js:1:1001529)
	$o (2.229d9a41.chunk.js:1:1001464)
	nc (2.229d9a41.chunk.js:1:1039229)
	ya (2.229d9a41.chunk.js:1:1018324)
	ya
	(anonymous function) (main.ace29e53.chunk.js:1:165353)
	u (2.229d9a41.chunk.js:1:1080248)
	(anonymous function) (2.229d9a41.chunk.js:1:1080033)
	r (2.229d9a41.chunk.js:1:327609)
	s (2.229d9a41.chunk.js:1:327812)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: Not allowed to request resource
	dispatchException (2.229d9a41.chunk.js:1:1083710)
	(anonymous function) (2.229d9a41.chunk.js:1:1079964)
	r (2.229d9a41.chunk.js:1:327609)
	c (2.229d9a41.chunk.js:1:327848)
	promiseReactionJob
```

**Comment by thundergreen** [comment]
I have aother issue on top of it. I added my api key to the config but it tells me that i don't have one

![image](https://user-images.githubusercontent.com/13320319/67162257-8c6fea00-f362-11e9-9d77-fbdd7bbe8b60.png)

![image](https://user-images.githubusercontent.com/13320319/67162260-942f8e80-f362-11e9-9a9a-89750d05d51a.png)

**Comment by TheCellMC** [comment]
@thundergreen I can confirm that I am also running into this issue

**Comment by TheCellMC** [comment]
So I've done some more logging, this issue seems to

**Comment by TheCellMC** [comment]
So I have done some more logging, this error seems to be linked to the CORS policy.

Here is the Chrome log:
`Access to fetch at 'http://feeds.bbci.co.uk/news/rss.xml' from origin 'HA-URL-REDACTED' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by PurelyNicole** [comment]
> I have aother issue on top of it. I added my api key to the config but it tells me that i don't have one
> 
> ![image](https://user-images.githubusercontent.com/13320319/67162257-8c6fea00-f362-11e9-9d77-fbdd7bbe8b60.png)
> 
> ![image](https://user-images.githubusercontent.com/13320319/67162260-942f8e80-f362-11e9-9a9a-89750d05d51a.png)

I was having this issue as well. You have to also select a source. The source dropdown doesn't auto-populate in Chrome, so if you have that issue start typing (ie CNN), clear that text out, and then you will have a list of news sources to select from.

**Comment by PurelyNicole** [comment]
I am also having the RSS issue. I have attempted with the following feeds:

- XKCD: https://xkcd.com/rss.xml
- CNN Top News: http://rss.cnn.com/rss/cnn_topstories.rss
- Best of Craigslist: https://www.craigslist.org/about/best/all/index.rss

**Comment by timmo001** [comment]
These all seem like issues on the side of the rss feeds as others work fine.

Some sites block other domains from requesting their feed.

 I will close this one as a known limitation

**Comment by PurelyNicole** [comment]
I do not believe this is the case, because I'm using the XKCD feed with IFTTT without issue.

I also tried the [RSS feed for my blog](http://puregeekery.net/feed) since I know it's not blocking other domains from accessing it. I am still seeing the same behavior.

**Comment by timmo001** [comment]
Looking into it, there is a workaround, but will require a proxy like:

https://cors-anywhere.herokuapp.com

**Comment by thundergreen** [comment]
Sounds good @timmo001  Would be nice getting this wirking :) I am ready to use proxy server... if there's a short writeup.. or do you plan to intergrate those directly in the addon?

**Comment by timmo001** [comment]
I would be more inclined to ask those afflicted to add this or another proxy site to the beginning of their URL.

So for @PurelyNicole you would simply need to change your url to https://cors-anywhere.herokuapp.com/https://www.puregeekery.net/feed/

**Comment by PurelyNicole** [comment]
That's pretty slick! I'll add that to the documentation as well.

**Comment by thundergreen** [comment]
doesnt work for me :/ I try to access this one: https://bit-titan.net/rss.php?rss=cat&cats=0|1020|1030|1120|1130|2070|2080&uid=5817&pk=c1bdbdcc66f69b53b4fa8ead04500d3a

**Comment by PurelyNicole** [comment]
@thundergreen: Works for me as  https://cors-anywhere.herokuapp.com/https://ttv2.myamity.info/rss.php?cat=3,54,52,8&passkey=XXX

Also, you may want to remove your passkeys and uids from these URLs.

**Comment by thundergreen** [comment]
@PurelyNicole Strange. If I enter thse in the RSS widget 

```
 https://cors-anywhere.herokuapp.com/https://ttv2.myamity.info/rss.php?cat=3&passkey=ec1b65dd2c745de4e61162f1f9f6014d
```
It keeps red and nothing is shown :/

**Comment by thundergreen** [comment]
ok not  working ... same issue .. it worked for a secoond an then It changed to not working :P
