### ISSUE TITLE
Remove docs for tune-in

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#697]
# Description

According to the Docker instruction, there's the TuneIn Radio but It seems removed?

**Comment by timmo001** [comment]
This has been gone for a while.

If you can link to where this is, or even open a PR to remove this line, that would be great.

**Comment by thundergreen** [comment]
https://hub.docker.com/r/timmo001/home-panel

In Feature section :P

**Comment by timmo001** [comment]
Oh in dockerhub

**Comment by timmo001** [comment]
Done
