### ISSUE TITLE
List of available icons & binary input status & permanent login to Home Assist

### ISSUE THREAD

**Issue by mchuc** [timmo001/home-panel#699]
# Description

1. no list of available icons to provide their names; only one type is suggested: thermometer. Does the program contain other icons? if so - please list these icons

2. it is not possible to set the background color change (as for a motion detector) for the binary input - there are charts available, but that's not it ... otherwise my Philips Hue detector generates (or maybe ConnBee2) the inscription: Detected and Clear .. And this is not in my language. Maybe better some icons: off / on or just changing the background?

3. I would also like to be able to save my login to Home Assist. Every time I log in to Home-Panel I have to log in to HomeAssist. Can you write it somehow?

## Suggested Actions

suggestions as above :)

**Comment by thundergreen** [comment]
1. : The icons are available at https://materialdesignicons.com/ Just chose one and put in the name in the icon field

2. issue has been raised already [](https://github.com/timmo001/home-panel/issues/500)

3. Good idea

**Comment by timmo001** [comment]
As thundergreen stated, the icons are avaliable from <https://materialdesignicons.com> and are the same icons HA use.

HA login is saved. If you log out of the app, you also log out of HA. This is so you can log into another server or user in HA with another user. Also, this could be a security risk leaving HA logged in  between user sessions

**Comment by mchuc** [comment]
I understand security considerations, but we now have the sequence:

Logging in to Home Panel * user 1
Logging in to Home Assistant * user 1
Logging out of Home Panel user 1

Log in to Home Panel * user 2
Logging in to Home Assistant * user 2
Logging out of Home Panel user 2

Logging in to Home Panel * user 1
Logging in to Home Assistant * user 1
Logging out of Home Panel user 1

and so on
...

and I would like to:
HP user1 login
RE-login to HA user1 (with connection host provided!) -> I want it to be saved for the given HP user1
Logging out HP user1

HP user1 login
(automatic login to HA from the data saved for user1)
HP Logout
