### ISSUE TITLE
Single User Mode - Bypass Login

### ISSUE THREAD

**Issue by michaeldavie** [timmo001/home-panel#700]
# Description

Support operating in a single user mode, eliminating the need for authentication.

This would be similar to the `allow_bypass_login` option of the `trusted_networks` authentication provider in Home Assistant ([link](https://www.home-assistant.io/docs/authentication/providers/#trusted-networks)), which bypasses the login screen for logins from a trusted network when a single user is available for login.

**Comment by timmo001** [comment]
This would not be possible since authentication is required to access the api.

Bypassing this would be a security risk
