### ISSUE TITLE
Rework Climate Widget

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#702]
# Description

I really love your work but I miss a bit the intuitive handling of some widgets. Especially the climate widet.

I'd rather go for a round widget like in lovelace

![image](https://user-images.githubusercontent.com/13320319/67166548-df609600-f390-11e9-8531-fe8a6b1b93fe.png)

## Suggested Actions

I would maybe shrink the hvac modes and maybe add sliders for target temperature setting.

Also like already mentioned in https://github.com/timmo001/home-panel/issues/698 I'd like to see the fan_mode inside this widget.

## Additional

My idea is  to have an intuitive widget. Maybe there could be a options / setting button with a pop-up which offers all supported hvac modes instead of having all modes in a list in the widget. Although it's very small and on a toucscreen it's sometimes a bit hard to change mvac mode or temperature.

**Comment by timmo001** [comment]
Adding fan modes is viable but this is a request to change the complete design of the entity card.

This is a decision I made and replicating lovelace is not the plan.
