### ISSUE TITLE
ADD fit to widget size I-Frame

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#707]
# Description
I wanna watch tmy Glances in an i-frame but it's too big. Is there a way to make the iframe to fit in the widget window size? As scrolling on my touchscreen is awful and the scrollbars are very small to catch them with my big fingers :P 

## Additional

![image](https://user-images.githubusercontent.com/13320319/67240608-1480ed00-f452-11e9-944a-a805deafcf5c.png)

**Comment by timmo001** [comment]
This is not possible. However, height is css, so you could try to size it accordingly
