### ISSUE TITLE
Change card icon and show slider

### ISSUE THREAD

**Issue by TheCellMC** [timmo001/home-panel#713]
# Description
In the documentation's screenshots, it seems that it is possible to change the icon and show the brightness slider of a card. However I'm not able to find the setting for that. Has it been removed?

**Comment by timmo001** [comment]
You can either press and hold the card, or make the card taller so it shows the slider

**Comment by TheCellMC** [comment]
Ok, thanks for the quick reply. And how can I change the icon of the card?
