### ISSUE TITLE
Dimmer function

### ISSUE THREAD

**Issue by mchuc** [timmo001/home-panel#722]
# Description
I have many lights in zigbee technology.
Individual lights are only displayed as binary on / off switches. Inability to control the brightness of light.

## How to reproduce the issue (if applicable)
New light has been added to deCONZ.
Home Assistant has been connected to the deCONZ gateway.
Entity light.your_name
has been added to the Home Panel as entity

**Comment by timmo001** [comment]
Please click and hold the card or increase the height of your card
