### ISSUE TITLE
Add person entity support

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#763]
# Description

I just had to update my automations as sometimes asuswrt component fails to scan my devices. So I now use person instead of device_tracker only. Like this I can put different device trackers to track if a person is at home.

Now I wanted to add person.xxx to the dashboard but it won't read out the state (home / not_home) like for device trackers.

Would it be possible to add person.xxx to the dashboard?

**Comment by timmo001** [comment]
Added https://github.com/timmo001/home-panel/commit/ba5957d34dc8a7f1f423f5cbafbf6786b65e3fbc
