### ISSUE TITLE
Issue with temperature control of climate card

### ISSUE THREAD

**Issue by FRHOME** [timmo001/home-panel#781]
# Description
Hey,
With my climate card, I can decrease the temperature but i can't increase it.
I have noticed this bug since a long.

My climate device is a Sensibo Sky.

Cheers

**Comment by thundergreen** [comment]
I also have a bit pain to increase or decrease the temp. It sometimes lags

**Comment by FRHOME** [comment]
there is no lag, im just unable to increase the temperature of the sensibo sky component. It's working with Lovelace.

**Comment by timmo001** [comment]
Unable to reproduce this issue, at least with the latest code.

I will release an update. Please reopen if you are still having issues after the update is released
