### ISSUE TITLE
[ADD] native state reporting

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#784]
# Description

I use an AppDaemon App called Shedy. This app creates an entity like this : 

```schedy_room.shedy_heating_bedroom```

with a state which shows the actual programmed mode for my climate.

Unfortunately HomePanel does not offer a native report. It only supports sensor. domains I guess.

Either I have to vreate a template sesnor or you might want to add the possibility not read out the state from no matter what domain / Entity

**Comment by timmo001** [comment]
I will only support official domains. AppDaemon is not supported
