### ISSUE TITLE
Graphs/Charts slow down UI

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#790]
# Description

I build a lot of dashboards with charts. But I have the feeling it becomes almost unresponsive.

Means sometimes changes are not taken into account. It takes ages to put some values in the widget editor.

## How to reproduce the issue (if applicable)

B>uild a dashboard with graphs

## Additional information

It might maybe help to deactivate pulling home assistant states while editing the widgets? It seems it blocks imense.

**Comment by thundergreen** [comment]
i realzed that without graphs it work better.. seems that graphs disturbs a bit

**Comment by timmo001** [comment]
This is a limitation of the library `recharts`. There are bots updating all the dependencies so hopefully they make some improvements. I have tried alternatives but none are as good as the current library.
