### ISSUE TITLE
Control the card size

### ISSUE THREAD

**Issue by Patrik-Hansson** [timmo001/home-panel#828]
# Description
The 1 x 1 hight/width is too big, at least when using low res screens.

## Suggested Actions
Would it be possible to change what represent 1 x 1 in Height / Width ?

**Comment by thundergreen** [comment]
Make 0.x instead for the size ..groups can't be smaller than 1 afaik but widgets do

**Comment by Patrik-Hansson** [comment]
> Make 0.x instead of 1 for the size ..groups can't be smaller than 1 afaik but widgets do

Thank you.
