### ISSUE TITLE
Double Tap Required to Interact

### ISSUE THREAD

**Issue by coyoteT** [timmo001/home-panel#841]
# Description
After a few seconds of the screen being idle, the bottom drawer disappears and requires a tap anywhere on the screen before you can interact with Home Panel. Once you tap and the bottom drawer displays, you can then control entities.

**Comment by wmmudde** [comment]
having the exact same issue. if you need more info i can help also.

**Comment by wmmudde** [comment]
Can developer please respond to this issue?

**Comment by timmo001** [comment]
I will add the ability to turn autohide of the navigation off since this appears to cause the issue
