### ISSUE TITLE
Persistant foother and a way to remove header

### ISSUE THREAD

**Issue by andlo** [timmo001/home-panel#857]
# Description
Persistant foother and a way to remove header

## Suggested Actions
It would be nice to have the foother persistant and a way to remove the header.

On realy small svreens like the pi 7" screen it is waste of screen to have a headerbar.

**Comment by timmo001** [comment]
These are already existing features. Check your settings page/section

**Comment by andlo** [comment]
I dont see any setting to remove header - only a way to hide it after a few seconds. But as soon someone touches the screen it reaear and all the cards are moved down.
