### ISSUE TITLE
Card layout on safari (#672)

### ISSUE THREAD

**Issue by air2** [timmo001/home-panel#881]
# Description

As explained in issue (#672) the card editing experience in safari sucks
This is likely related to an issue in safari.
However when I edit the class of the lowest box (the one overlayed by another box) into:
MuiGrid-item-xs-column instead of MuiGrid-direction-xs-column it works fine in Safari.
I have no experience at all with MuiGrid so maybe this is just a stupid suggestion, but I would really appreciate it if this could be changed (maybe only for safari browsers) it would make the whole card editing experience work again.

I added the red rectangle to the screenshot to show the place I where the inconsistency is 
Before:
<img width="562" alt="Screenshot 2020-01-12 at 10 36 30 " src="https://user-images.githubusercontent.com/3084096/72217015-3659af80-3529-11ea-8099-678d9886e801.png">

After:
<img width="562" alt="Screenshot 2020-01-12 at 10 49 56 " src="https://user-images.githubusercontent.com/3084096/72217028-5e491300-3529-11ea-886c-31bf59d5dd14.png">

**Comment by timmo001** [comment]
I'd still be cautious to say this is a bug in safari as any other browser has no issues.

Unfortunately, I am unable to test this without a mac so this will be up to contributors (which are [welcome](https://github.com/timmo001/home-panel/blob/master/.github/CONTRIBUTING.md) by the way) to fix for the 'odd' browser as it's called

**Comment by timmo001** [comment]
The packages for material-ui have been updated quite a bit since this issue was opened.

Please feel free to reopen this issue if this issue is still occurring after updating to the latest version of the app I am about to release. Thanks
