### ISSUE TITLE
How do I set up charts?

### ISSUE THREAD

**Issue by jimmyeao** [timmo001/home-panel#914]
How do I set up charts? They are shown in the example theme, but no explanation of how to configure it

**Comment by thundergreen** [comment]
@jimmyeao just add an sensr and then u get the option in the widget cinfigurator below to add a chart.

**Comment by timmo001** [comment]
When editing a card, there will be an option to add a chart when using an entity that produces data like a sensor. Be sure to use the options as currently there are some performance issues with large amounts of data in charts

![image](https://raw.githubusercontent.com/timmo001/home-panel/master/docs/resources/screen-config-ui.gif)

Any future queries will be best answered here:

https://community.home-assistant.io/t/home-panel-a-web-frontend-for-controlling-the-home/62597?u=timmo001

**Comment by jimmyeao** [comment]
cool, thanks, Need to figure out why the chart displays on windows but not on chromium on the pi
