### ISSUE TITLE
Add home-panel integration

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#922]
# Description

I'd love to see Homepanel being able to also listen to home Assistant events. Like Appdaemon Hadashboard . Means you can control home panel via home Assistant events. 

## Suggested Actions

Binary sensor on -->. Show cam stream full screen 

Backgrounds / themes based on lux

## Additional

I saw a pull request back in some weeks on GitHub repo of home Assistant but it disappeared unfortunately. Where's the project gone ?

**Comment by timmo001** [comment]
This exists, and is also an open PR for Home Assistant Core:

https://github.com/home-assistant/home-assistant/pull/27540
