### ISSUE TITLE
Can't create account after install in hassio

### ISSUE THREAD

**Issue by sotatech** [timmo001/home-panel#95]
# Description
I'm running version 0.1.6 of Home Panel plug-in with HA 0.77.3 and cannot create an account to login. For the API URL I use https://hass.mydns.com:3234 and I get API is alive on this URL. The home assistant host is hass.mydns.com:8123. I'm using LetsEncrypt (not DuckDNS) and SSL.
In the logs I get:
HASS Request URL: https://hass.mydns.com:8123/api/?api_password=<password> Forbidden

I don't see anything in the HA logs.

**Comment by timmo001** [comment]
Are you using the correct HASS API Password?

**Comment by sotatech** [comment]
Yes, I logged in from a new private window to get HA to request the API password, and I could log in successfully. The message that appeared briefly on the home-panel pages was:
Error: 400 - An error occurred while connecting to HASS: Error: Unauthorized

Finally got it to work just now by adding the docker subnet (172.30.33.0/24) to trusted_networks in configuration.yaml.

Thanks.

**Comment by timmo001** [comment]
Glad you got it working 👍
