### ISSUE TITLE
No units of measure or weather icon in 2.7.2

### ISSUE THREAD

**Issue by michaeldavie** [timmo001/home-panel#995]
# Description

Units of measure and the weather condition icon are no longer displayed in v2.7.2

## How to reproduce the issue (if applicable)

N/A

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/16008714/76369369-b02fce80-6309-11ea-8256-0b676987dacd.png)

## Additional information

Using `latest` Docker image, `sha256:506a8326922b94aba92316f714648a62c1b34c8d990a7f45cd29655fc87d1a58`

**Comment by michaeldavie** [comment]
Still present in 2.7.3

**Comment by michaeldavie** [comment]
I've rolled back to 2.6.0 and confirmed that the units are present.
![image](https://user-images.githubusercontent.com/16008714/77701287-50cdf180-6f8c-11ea-98bc-a11e5901c06f.png)

**Comment by mjoshd** [comment]
May I ask how you were able to roll back? I I'm using the latest available version in Home Assistant Core and have been looking around but have been unable to find a command which would allow installation of an older version.

**Comment by michaeldavie** [comment]
I use the Docker version of home-panel, so I just pulled the 2.6.0 version from Docker Hub.

**Comment by mjoshd** [comment]
I just now installed the Portainer addon and was able to use that to pull & install v2.6.0 like you mentioned and it's back to showing the unit_of_measurement again. 

Hopefully @timmo001 can fix this in the [official Hass.io addon](https://github.com/hassio-addons/addon-home-panel) at some point. 

@michaeldavie Thanks for the tip!

**Comment by michaeldavie** [comment]
Thanks! I've switched to 2.8.0 and confirmed that the units are back. One minor quibble: would it be possible to include a space between the value and the unit as it was in 2.6.0 (pictured above)? In 2.8.0 there is no separation:

![image](https://user-images.githubusercontent.com/16008714/79808482-e7978f00-833b-11ea-8910-9e822259d461.png)
